<div class="container main">
    <div class="row">
        <div class="col-md-12">
            <h1>Background</h1>
            <p>The death of Gopal Krishna Gokhale on 19th February 1915 evoked an outburst of grief and sense of loss throught the country. Leaders like Balagangadhar Tilak and Mahatma Gandhi paid rich tributes to the departed leader. There was a desire every where to make an organised effort to serve the country after the example of gokhale.</p>
            <h2>1915-1941</h2>
            <p>In Bangalore a largely attended public meeting was held on <strong>25th February 1915</strong> at which <strong>Sir M.Visveswaraya</strong>, then Dewan of Mysore, spoke in appreciation of Gokhale's personality and his work. Inspired by the speeches of national leaders and others, a small group of young men decided to start an association called The <strong>Mysore Social Service League</strong>. Among those who took active interest in that endeavour may be mentioned <strong>D.V.Gundappa, K.S.Krishna Iyer. A.R.Nageshwara Iyer, N.Narasimha Murthy, M.G.Varadachar, C.S.Anantha Padmanabha Iyer, S.Surya Prakash, Mokshagundam Krishna Murthy, Belur Srinivasa Iyengar, B.V.Subba Rao and K.Bheema Rao</strong>. It is this small group which decided to invite Mahatma Gandhi to Bangalore in May 1915 and requested him to bless their idea. Gandhiji was touring in South India at that time, and had proposed to visit Madras. A telegram was sent to him and the invitation was accepted.</p>
            <p>The visit of Mahatma Gandhi - his first visit to Bangalore - evoked great enthusiasm among the public and the function was a great success. M.Venkatakrishnaiya, the Grand Old Man of Mysore, came specially to take part in the meeting. Enthused by the public appreciation, the League drew up a programme of work. It arranged several public lectures. It organised two night schools and took up relief measures during the epidemic of influenza in 1918-19. The epidemic snatched away some members of the League, and the personal circumstances of other members turned unfavourable for public work. During the next ten years the dream of public service remained only in the hearts of these young men who were by then popularly known as the Gokhale group.</p>
            <p>The urge to revive the idea came during 1930 due to the conditions then prevailing in the country. To make democracy safe and smooth, a non-partisan and well-informed citizens' group was the need of the day. To organize such an agency was the purpose of the Gokhale Institute of Public Affairs.</p>
            <p>During 1939 a draft of the conspectus was prepared by D.V.Gundappa and submitted to Rt.Hon. V.S.Sreenivasa Sastri. Incorporating his valuable suggestions, a letter of appeal was prepared to raise an initial fund of Rs.5,000/-. However, it had to be defered for various reasons.</p>
            <p>Another effort was made in 1941 about the time of the introduction of new constitution in Mysore. A course of lectures was arranged to enlighten the public about the New Constitution. Four meetings were arranged. The first meeting of the Gokhale Institute of Public Affairs was called on 22nd May 1941 in the National High School. It drew a packed audience among whom were noted journalists, political workers, members of legislature and other prominent citizens. D.V.Gundappa delivered the first day's lecture; the second, third and fourth meetings were addressed by M.A.Gopalaswamy Iyengar, M.P.Somasekhara Rao and V.Sitaramaiah respectively.</p>
            <h2>At the initial stage</h2>
            <p>A renewed and final effort - now for the fourth time - at founding the Gokhale Institute was made towards the end of 1944 and letters of appeal were once again addressed. The response was encouraging. A meeting was called on 18th February 1945 at D.V.Gundappa's residence in Nagasandra Road. The meeting adopted the draft rules and appointed a Council of Management, Congratulatory messages had been received from Gopalaswamy Ayyangar, Sir Mirza M. Ismail and others. The Institute in the present form was thus born on 18th February 1945. However, as the needed building was not available, it was only on 2nd July 1946 that the first lecture was arranged after securing a building. That meeting was addressed by Hrudayanath Kunzru, then president of the Servants of India Society.</p>
            <p>The Study Circle was started on 15th December 1947 and the first book taken up for study was John Stuart Mill's On Liberty, Since then many Classics in English, Samskrita and Kannada have been studied. On 15th August 1948 B.P.Wadia, Director of the Indian Institute of World Culture, Bangalore, declared the Library of the G.I.P.A. open for the public use. The library now has a rare collection of valuable books, and is constantly used by the general public as well as by research scholars.</p>
        </div>
    </div>
</div>
